Feature/header
anamanoilo/team-proj-filmoteka pull request #41
Opened 2022-03-05 21:56 UTC by andrpoch

Изменил логотип.
Сделал смену темы.
Сними с кнопок  watched и queue is-hidden посмотри эффекты.
Будут изменения пиши.

2022-03-05 21:59 UTC, andrpoch commented
И там в mani.html подключил файлы для лампочек на чекбоксе

2022-03-09 11:21 UTC, anamanoilo requested changes
класно, що зробив зміну теми, але треба пофіксити її

2022-03-09 11:21 UTC, anamanoilo commented on src/partials/header.html
> +          <ul class="header__logo_list">
помилка з валідатора: Element [ul] not allowed as child of element [span] in this context. (Suppressing further errors from this subtree.)
але я взагалі думаю, що варто повернути тег [p] з текстом Filmoteka, як було раніше.
робити список з лішками по одній літері - це просто семантика каже до побачення. у нас на сайті більше ніде не повторюється назва Filmoteka, вона просто не проіндексується СЕО, та і для читалок це буде брєд. сама іконка красиво пульсує оранжевим, це точно залишаємо :)

2022-03-09 11:21 UTC, anamanoilo commented on src/partials/header.html
> +        <label class="theme-switch">
помилка з валідатора: Element [div] not allowed as child of element [label] in this context.
плюс прибери взагалі цю всю зміну теми з тегу [nav]. до навігації це не відноситься

2022-03-09 11:21 UTC, anamanoilo commented on src/partials/header.html
> -      <a href="#" class="library__btn watched__link is-active is-hidden">Watched</a>
оранжевою має бути активна кнопка ('watched' або 'queue', залежно від того, на яку натиснули; при відкритті library оранжевою має бути 'watched'). аутлайни, яки ти додав, там не потрібні, на ховер можеш додати box-shadow, так як в модалці зроблено. щоб всюди було одноково, тільки колір зміниш, щоб цей box-shadow було видно

2022-03-09 11:21 UTC, anamanoilo commented on src/images/symbol-defs 2.svg
> +<!-- <symbol id="icon-film" viewBox="0 0 32 32">
прибери зайві коментарі, будь ласка

2022-03-10 13:22 UTC, andrpoch commented on src/partials/header.html
> +        <label class="theme-switch">
не знаю шо з цим можна зробити, може забрати цю лампочку?

2022-03-15 16:38 UTC, merged